export QT_QPA_PLATFORMTHEME=gtk2
export TERM=xterm-kitty
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=firefox
export PATH=$PATH:$HOME/.local/bin
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
